# CrewGraph AI Development Environment
# Author: Vatsal216
# Created: 2025-07-23 06:03:54 UTC

version: '3.8'

services:
  crewgraph-ai:
    build: .
    container_name: crewgraph-ai-app
    ports:
      - "8080:8080"
    environment:
      - CREWGRAPH_ENV=development
      - CREWGRAPH_LOG_LEVEL=DEBUG
    volumes:
      - ./examples:/app/examples
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - crewgraph-network

  redis:
    image: redis:7-alpine
    container_name: crewgraph-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - crewgraph-network

  monitoring:
    image: grafana/grafana:latest
    container_name: crewgraph-monitoring
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - crewgraph-network

volumes:
  redis_data:
  grafana_data:

networks:
  crewgraph-network:
    driver: bridge