# Horizontal Pod Autoscaler for CrewGraph AI
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: crewgraph-ai-hpa
  namespace: crewgraph-ai
  labels:
    app: crewgraph-ai
    component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crewgraph-ai
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: workflow_queue_length
      target:
        type: AverageValue
        averageValue: "10"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
---
# Vertical Pod Autoscaler for Resource Right-sizing
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: crewgraph-ai-vpa
  namespace: crewgraph-ai
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crewgraph-ai
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: crewgraph-ai
      minAllowed:
        cpu: 100m
        memory: 512Mi
      maxAllowed:
        cpu: 4
        memory: 8Gi
      controlledResources: ["cpu", "memory"]
---
# Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: crewgraph-ai-pdb
  namespace: crewgraph-ai
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: crewgraph-ai